# Generated by Django 4.1 on 2022-09-07 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=models.CharField(default='Золото', max_length=30, verbose_name='Цвет/Материал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Здесь будет описание', verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(default=30, verbose_name='Размер в мм'),
        ),
    ]
