# Generated by Django 4.1 on 2022-09-17 16:49

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug_alter_gallery_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[630, 630], upload_to='products/', verbose_name='Изображение'),
        ),
    ]
